[package]
name = "numutil"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.23.0", features = ["tts", "wgpu", "x11", "default_fonts"], default-features = false }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
